[AppSettings]
APP_VERSION = "0.0.1"
CSS_PATH = "app.css"

[AppInfo]
MODEL = "Модель для сопоставления вакансии с ПУДами изменена на {}"

[InformationMessages]
NOTI_IN_DEV = "В разработке"
STEP_1 = "Шаг 1: Ввод персональных данных"
STEP_2 = "Шаг 2: Чат"
SURNAME = "Введите Вашу фамилию"
USERNAME = "Введите Ваше имя"
USER_AFFILIATION = "Укажите Вашу принадлежность"
NOTI_AUTH = [
    "Заполните Ваши персональные данные",
    "Все персональные данные успешно запонены",
]
SKILLS_NOT_DEFINED = "Навыки не определены"
FROM_TO = "От {} до {}"
MODEL = "Выберите модель"

[OtherMessages]
IMPORTANT = "Обязательно"
AUTH = "Запомнить персональные данные"
JOB_DESC = "Введите название вакансии и ее описание"

[Labels]
SURNAME = "Фамилия"
USERNAME = "Имя"
USER_AFFILIATION = "Принадлежность"
CHATBOT = "Подбор предметов из ВШЭ для определенной вакансии"
TOP_SUBJECTS = "Количество предлагаемых предметов"
MAX_SKILL_WORDS = "Максимальное количество слов в одном навыке"
MODEL = "Модель для сопоставления вакансии с ПУДами"

[EducationLevels]
ALL_LEVELS = "Бакалавриат, Специалитет, Магистратура, Аспирантура"
NONE_LEVELS = "None"

[HtmlContent]
LEVELS_EDUCATION_LABEL = "Уровни обучения:"
LEVEL_EDUCATION_LABEL = "Уровень обучения:"
SUBJECT_LABEL = "Дисциплина:"
ID_SUBJECT_LABEL = "ID дисциплины:"
DEPARTMENT_LABEL = "Кафедра:"
FACULTY_LABEL = "Факультет кафедры:"
CAMPUS_LABEL = "Кампус:"
AUDIENCE_LABEL = "Охват аудитории:"
FORMAT_LABEL = "Формат изучения:"
SKILLS_LABEL = "Получаемые навыки:"

[TabCreators]
"⭐ Приложение" = "app_tab"
"⚙️ Настройки" = "settings_app_tab"
"💡 О приложении" = "about_app_tab"
"🎭 Об авторах" = "about_authors_tab"
"📋 Зависимости" = "requirements_app_tab"

[StaticPaths]
MODELS = "models"
IMAGES = "images"
PUDS = "data/ПУДы.parquet"
PUDS_EMBEDDINGS = "data/ПУДы_эмбеддинги.safetensors"
RU_SUBJECTS = "data/Названия_дисциплин_для_эмбеддингов.parquet"
PUDS_SKILLS = "data/ПУДы_навыки.parquet"

[DataframeHeaders]
RU_ID = "ID дисциплины БУП ППК (АСАВ)"
RU_SUBJECTS = [
    "Русскоязычное название дисциплины",
    "Факультет кафедры, предлагающей дисциплину",
    "Кампус кафедры, предлагающей дисциплину",
    "Кафедра, предлагающая дисциплину",
    "Уровень обучения",
    "Период изучения дисциплины",
    "Охват аудитории",
    "Формат изучения"
]
SUBJECTS_YEAR = "Период изучения дисциплины"
SUBJECTS_FULL = [
    "Аннотация",
    "Список разделов (названия и описания)",
    "Список планируемых результатов обучения РПУДа",
]
SUBJECTS_FULL_INFO = "full_info"

[Settings]
DROPDOWN_USER = [
    "-",
    "Студент",
    "Преподаватель",
    "Представитель учебного офиса",
]
USER_MAX_LENGTH = 20
TOP_SUBJECTS_RANGE = [1, 40]
TOP_SUBJECTS = 20
MAX_SKILL_WORDS_RANGE = [1, 10]
MAX_SKILL_WORDS = 4
PRIORITY = [
    "Бакалавриат",
    "Специалитет",
    "Бакалавриат, Специалитет",
    "Бакалавриат, Магистратура",
    "Магистратура",
    "Аспирантура",
    "-",
    "nan",
]

[Models]
TASK = "text-matching"
SBERT = [
    "paraphrase-multilingual-MiniLM-L12-v2",
    "jina-embeddings-v3",
]

[Requirements]
LIBRARY = "Библиотека"
RECOMMENDED_VERSION = "Рекомендованная версия"
CURRENT_VERSION = "Текущая версия"